bootnodes=["enode://5e15792a10fefc24bf495c44896734a177ed01857b8b162879b317c5fdcd7f16a0cb8af877a6bb510dc0eb15990cfa92deaa85a87c9edd03e833d928eb6f9f78@18.202.38.195:30303","enode://f5a31862af9adbe702562481663c0fecfc3fa4a6e5a21b16907e23e537f641d40ee361880d68e4d5d97a105a06fe6775c4fca07e507d0ea322018dc0f754546b@52.16.154.220:30303","enode://abe1d7baf32e88849526f01369bd432119188ff3f8e369d1abab89e75e14557c33322ea8eced2ab2b4722cf3e3301ef5af9385411c509060e97aa35f1ea1b60c@158.176.139.92:30303","enode://76af726fa65c4a1fb6e150960eda7e5ac12a58f34dc544911190c44ee32dff3357a5c323639626e9b35e5c3fef4e2a07b21dc82d099560808ae8e4ae870425d5@5.153.57.78:30303"]
data-path="/opt/besu/data"
genesis-file="/config/besu/genesis.json"
min-gas-price=0
privacy-enabled=true
privacy-marker-transaction-signing-key-file="/keys/besu/signer.key"
privacy-public-key-file="/keys/orion/orion.pub"
privacy-url="http://orion:8888" # orion clienturl
host-whitelist=["*"]
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="9545"
rpc-http-enabled=true
rpc-ws-enabled=true
logging="ERROR"